### PR TITLE
Custom MvM missions fixes

### PR DESCRIPTION
**Pull request by mtxfellen**
Fixes two things:
- Capture the Flag HUD showing when playing bombless MvM missions
- Scoreboard playerlist cutting off players if more than six are on a team.

The first fix listed works as intended with no side effects.
The second 'fix' is admittedly a hacky solution in which the playerlist is just made arbitrarily long; without completely reshuffling the MvM scoreboard, there's no good HUD-only fix for this, but I figure it's better than obscuring that information entirely? Though, of course, please deny that 'fix' if it's outside the scope of the project.

These changes have no visual impact on the HUD when otherwise playing Valve standard MvM missions.

### CODE REVIEW

**Comment by mtxfellen** [comment]
Added red team playercount center aligned under difficulty label, should be non-intrusive in 'normal' play and hopefully useful on custom missions with extended player counts.

**Comment by CriticalFlaw** [comment]
Could you post comparison screenshots please?

**Comment by mtxfellen** [comment]
<details>
  <summary>Capture the Flag HUD fix</summary>
  
  Doesn't seem possible to also remove the bomb upgrade indicators with this method.
  Has no impact on HUD when playing Valve missions.

  
  
</details>

<details>
  <summary>Added RED Playercount</summary>
  
  Difficulty panel also needed moving because in its original position it can intersect with the wavebar on some missions. Difficulty panel is placed below the player count because it isn't visible on custom missions.

  
  
</details>

<details>
  <summary>Increased playerlist length past background</summary>
  
  Doing a real fix for this without departing from the Valve-style scoreboard seems tough, as the actual background colour to each player on the scoreboard is hardcoded to change based on their alive status, making a dynamically resizing scoreboard seemingly impossible unlike in casual.
  
  ```
    // excerpt from tf_hud_mann_vs_machine_scoreboard.cpp
	// change color based off alive or dead status. Also slightly different if its local player since the name is highlighted.
	if ( bAlive )
	{
		UpdatePlayerAvatar( playerIndex, pKeyValues );
		fgClr = g_PR->GetTeamColor( TF_TEAM_RED );
		bgClr = Color( 0, 0, 0, 0 );
	}
	else
	{
		pKeyValues->SetInt( "avatar", m_iImageDead );
		fgClr = Color( 117, 107, 94, 255 );
		bgClr = Color( 78, 78, 78, 150 );
	}
  ```

  
  Has no impact on HUD when playing Valve missions.

  
  
</details>

**Comment by CriticalFlaw** [comment]
I removed redundant lines for the MvM player count placement because only x/y pos needed to be changed for the desired effect. I also reverted the player list extension because it doesn't fix the problem only make it worst by creating overlaps. Best to leave that one to valve.

**Comment by CriticalFlaw** [comment]
Everything else looks good. Merging.

**Pull request merged**
