### PR TITLE
Fix "null.mp3" console warning

### PR DESCRIPTION
**Pull request by Kruphixx**

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
There's already a null.wav file in https://github.com/CriticalFlaw/tf2hud.fixes/tree/main/sound/vo

Is null.mp3 something new, linux-related or is a result of the new 64bit update?

**Comment by Kruphixx** [comment]
It's a new thing from the 64bit update.

**Comment by CriticalFlaw** [comment]
Do we still need to keep null.wav then?

**Comment by Kruphixx** [comment]
Not sure, I see other huds keeping that file but maybe the creator just forgot to remove it.

I'd say it can be removed (can't do it myself at the moment though).

**Comment by CriticalFlaw** [comment]
Lets try it and see if the null.wav error comes up again

**Pull request merged**
