### PR TITLE
Fixed syringe gun ammo cutoff in linux

### LINKED ISSUE #50: Syringe ammo counter representing "40" as "4..."
### Issue
When using any of the syringe guns, rather than a full clip showing 40, it will instead display "4...". 

### Specifications
Fedora Linux 35
Using the community branch up to the April 3rd, 2022 version
Playing at 1920x1080

### Screenshot
Ammo

### PR DESCRIPTION
**Pull request by impale1**
Fixes #50

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
Is wide = 56 enough to cover all cases? Does the issue persist when you fire the weapon and the ammo count ticks down?

**Comment by Eerorri** [comment]
Bug persists on the beta, also tried out emptying SMG with ammo clip upgrades in MVM and the fix seems fine

**Comment by CriticalFlaw** [comment]
@Eerorri thank you for testing. Will keep this PR open until it is resolved

**Comment by Eerorri** [comment]
@impale1 The fix works on both

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Fixes/pull/227

**Pull request closed without merging**
