### PR TITLE
Fixed status icons overlapping max health (again)

### LINKED ISSUE #214: [BUG] Status icons overlap max health
**Specifications**
Operating system - Windows 11 Enterprise 22H2
Resolution - 1920x1080

**Screenshots**
mfd

### PR DESCRIPTION
**Pull request by impale1**
Closes #214 
All the other status icons don't overlap the max health, except for Mad Milk, so I had to move the status icons up a bit more again

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
This is the third PR for the same issue. Have you tested it this time?

**Comment by CriticalFlaw** [comment]
Also, instead of moving all the icons why not just put the max health slightly higher so it does not overlap the killstreak counter like the original fix did.
image

**Comment by CriticalFlaw** [comment]
It may no longer be used because I don't see any condition that would match to it https://wiki.teamfortress.com/wiki/Cheats#addcond

**Comment by mtxfellen** [comment]
PlayerStatus_SpyMarked section can likely be removed entirely, as it pertains to the cut Tranquilizer Gun.

**Comment by CriticalFlaw** [comment]
Done in 8c16dd8ae41c86740941a4caf0cca51bf7b837f7. Reverted all extraneous changes and only moved the max health value.

**Pull request closed without merging**
