### PR TITLE
Main menu/store/replays button consistency

### PR DESCRIPTION
**Pull request by Kruphixx**
Adjusts the "Items", "Close" and "Back" buttons so they're all in the same position. In default TF2 the issue is definitely most noticeable in the store with the "Close" button.

Short video showing the change:

https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/50501742/0281fe08-4ef1-4d83-9d07-4f03bde91ff3

### CODE REVIEW

**Comment by Kruphixx** [comment]
Additionally, adjusted position of the panels in the main menu so they're aligned with the "items" button.

**Comment by CriticalFlaw** [comment]
Thanks! I vaguely recall this being in the mod and may have been erroneously removed.

**Comment by CriticalFlaw** [comment]
@Kruphixx Will need to revert the medal placement change because it does not look good in 4:3 
image

**Comment by Kruphixx** [comment]
> @Kruphixx Will need to revert the medal placement change because it does not look good in 4:3 image

I've done some testing and this only seems to happen on that specific 4:3 resolution and literally nothing else (1280x1024). Don't see a way of fixing this

**Pull request merged**
